task: detection

num_classes: 4
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./configs/dataset/ThermalDogsAndPeople/train
    ann_file: ./configs/dataset/ThermalDogsAndPeople/train/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 0
  drop_last: True 

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./configs/dataset/ThermalDogsAndPeople/valid/
    ann_file: ./configs/dataset/ThermalDogsAndPeople/valid/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 0
  drop_last: False
  
